# Generated by Django 5.2.10 on 2026-01-15 19:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimalModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "species",
                    models.CharField(
                        choices=[
                            ("mouse", "Mouse"),
                            ("rat", "Rat"),
                            ("zebrafish", "Zebrafish"),
                            ("drosophila", "Drosophila"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("strain", models.CharField(max_length=100)),
                ("genetic_background", models.TextField(blank=True)),
                (
                    "age_weeks",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "weight_grams",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("health_status", models.CharField(max_length=200)),
                ("source", models.CharField(max_length=200)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="animal_models",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["species", "name"],
            },
        ),
        migrations.CreateModel(
            name="CellLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "cell_type",
                    models.CharField(
                        choices=[
                            ("cancer", "Cancer"),
                            ("normal", "Normal"),
                            ("primary", "Primary"),
                            ("stem", "Stem Cell"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("origin", models.CharField(max_length=200)),
                ("tissue_type", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("passage_number", models.IntegerField(default=0)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cell_lines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cell Line",
                "verbose_name_plural": "Cell Lines",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Experiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("on_hold", "On Hold"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planning",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("lab", models.CharField(max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "principal_investigator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="experiments_pi",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Documentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("note", "Note"),
                            ("protocol_amendment", "Protocol Amendment"),
                            ("incident_report", "Incident Report"),
                            ("data_quality_report", "Data Quality Report"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("content", models.TextField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "file_attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="experiment_docs/%Y/%m/%d/"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentation",
                        to="research.experiment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="ExperimentAnimal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("treatment_group", models.CharField(max_length=100)),
                ("dosage", models.CharField(blank=True, max_length=100)),
                (
                    "route_of_administration",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "number_of_animals",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "animal_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="research.animalmodel",
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiment_animals",
                        to="research.experiment",
                    ),
                ),
            ],
            options={
                "unique_together": {("experiment", "animal_model", "treatment_group")},
            },
        ),
        migrations.AddField(
            model_name="experiment",
            name="animal_models",
            field=models.ManyToManyField(
                related_name="experiments",
                through="research.ExperimentAnimal",
                to="research.animalmodel",
            ),
        ),
        migrations.CreateModel(
            name="ExperimentSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("treatment", models.CharField(blank=True, max_length=255)),
                ("concentration", models.FloatField(blank=True, null=True)),
                ("concentration_unit", models.CharField(blank=True, max_length=50)),
                ("duration_hours", models.FloatField(blank=True, null=True)),
                ("replicate_number", models.IntegerField(default=1)),
                ("notes", models.TextField(blank=True)),
                (
                    "cell_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="research.cellline",
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiment_samples",
                        to="research.experiment",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("experiment", "cell_line", "treatment", "concentration")
                },
            },
        ),
        migrations.AddField(
            model_name="experiment",
            name="cell_lines",
            field=models.ManyToManyField(
                related_name="experiments",
                through="research.ExperimentSample",
                to="research.cellline",
            ),
        ),
        migrations.CreateModel(
            name="GeneExpression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gene_name", models.CharField(max_length=100)),
                ("gene_id", models.CharField(blank=True, max_length=50)),
                ("expression_level", models.FloatField()),
                (
                    "measurement_method",
                    models.CharField(
                        choices=[
                            ("qpcr", "qPCR"),
                            ("rna_seq", "RNA-Seq"),
                            ("microarray", "Microarray"),
                            ("in_situ", "In Situ Hybridization"),
                            ("immunohistochemistry", "Immunohistochemistry"),
                            ("western_blot", "Western Blot"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("measurement_date", models.DateTimeField(auto_now_add=True)),
                ("reference_gene", models.CharField(blank=True, max_length=100)),
                ("confidence_interval", models.CharField(blank=True, max_length=100)),
                (
                    "p_value",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "animal_sample",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="research.experimentanimal",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gene_expressions",
                        to="research.experimentsample",
                    ),
                ),
            ],
            options={
                "ordering": ["-measurement_date"],
            },
        ),
        migrations.CreateModel(
            name="ResearchProtocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "experiment_type",
                    models.CharField(
                        choices=[
                            ("in_vitro", "In Vitro"),
                            ("in_vivo", "In Vivo"),
                            ("ex_vivo", "Ex Vivo"),
                            ("computational", "Computational"),
                        ],
                        max_length=20,
                    ),
                ),
                ("objective", models.TextField()),
                ("methodology", models.TextField()),
                ("version", models.IntegerField(default=1)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="protocols",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_date"],
            },
        ),
        migrations.AddField(
            model_name="experiment",
            name="protocol",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="experiments",
                to="research.researchprotocol",
            ),
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parameter_name", models.CharField(max_length=255)),
                ("value", models.FloatField()),
                ("unit", models.CharField(max_length=50)),
                ("measurement_date", models.DateTimeField(auto_now_add=True)),
                ("method", models.CharField(max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "animal_measurement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="research.experimentanimal",
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="research.experiment",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="research.experimentsample",
                    ),
                ),
            ],
            options={
                "ordering": ["-measurement_date"],
            },
        ),
    ]
