# Generated by Django 5.2.11 on 2026-02-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="animalmodel",
            name="index_number",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="cellline",
            name="index_number",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="documentation",
            name="index_number",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="experiment",
            name="index_number",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="experimentanimal",
            name="index_number",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="experimentsample",
            name="index_number",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="geneexpression",
            name="index_number",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="researchprotocol",
            name="index_number",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="result",
            name="index_number",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
