# Generated by Django 5.2.11 on 2026-02-11 18:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0003_populate_index_numbers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="animalmodel",
            index=models.Index(
                fields=["created_by"], name="research_an_created_5cdee7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="animalmodel",
            index=models.Index(
                fields=["species", "strain"], name="research_an_species_55c745_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cellline",
            index=models.Index(
                fields=["created_by"], name="research_ce_created_850d67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cellline",
            index=models.Index(fields=["name"], name="research_ce_name_db3b2a_idx"),
        ),
        migrations.AddIndex(
            model_name="documentation",
            index=models.Index(
                fields=["experiment"], name="research_do_experim_4d2d0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentation",
            index=models.Index(
                fields=["author"], name="research_do_author__612931_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentation",
            index=models.Index(
                fields=["document_type"], name="research_do_documen_e2156c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="experiment",
            index=models.Index(
                fields=["principal_investigator"], name="research_ex_princip_ab05aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="experiment",
            index=models.Index(
                fields=["protocol"], name="research_ex_protoco_c87197_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="experiment",
            index=models.Index(fields=["status"], name="research_ex_status_9fdde3_idx"),
        ),
        migrations.AddIndex(
            model_name="experiment",
            index=models.Index(
                fields=["start_date"], name="research_ex_start_d_818c00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="experimentanimal",
            index=models.Index(
                fields=["experiment"], name="research_ex_experim_472957_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="experimentanimal",
            index=models.Index(
                fields=["animal_model"], name="research_ex_animal__e44740_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="experimentsample",
            index=models.Index(
                fields=["experiment"], name="research_ex_experim_385ca9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="experimentsample",
            index=models.Index(
                fields=["cell_line"], name="research_ex_cell_li_7b7056_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="geneexpression",
            index=models.Index(
                fields=["sample"], name="research_ge_sample__89389b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="geneexpression",
            index=models.Index(
                fields=["animal_sample"], name="research_ge_animal__73eefb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="geneexpression",
            index=models.Index(
                fields=["gene_name"], name="research_ge_gene_na_67535f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="researchprotocol",
            index=models.Index(
                fields=["created_by"], name="research_re_created_161fc7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="researchprotocol",
            index=models.Index(
                fields=["experiment_type"], name="research_re_experim_766e21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="result",
            index=models.Index(
                fields=["experiment"], name="research_re_experim_d8f915_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="result",
            index=models.Index(
                fields=["sample"], name="research_re_sample__0d8c0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="result",
            index=models.Index(
                fields=["animal_measurement"], name="research_re_animal__01190a_idx"
            ),
        ),
    ]
